name: bic086
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.8.8
  - snakemake==6.2.1
  - nox
  - pre-commit
  - pytest
  - pytest-clarity
  - six
  - pytest-sugar
  - pytest-mock
  - pytest-cov
  - coverage
  - black
  - isort
  - safety
  - typeguard
  - mypy
  - flake8
  - flake8-bugbear
  - flake8-docstrings
  - flake8-comprehensions
  - darglint
  - pip==21.1
  - pip:
    - flake8-annotations
    - flake8-bandit
    - flake8-pytest-style
    - flake8-spellcheck
    - pyproject-flake8
