[tool.semantic_release]
branch = "main"
version_variable = [
        "scripts/__init__.py:__version__"
]
changelog_file = "CHANGELOG.rst"
upload_to_pypi = false
upload_to_release = false

[tool.coverage.run]
branch = true
source = ["scripts"]
omit = ["*/__init__.py"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
        'pragma: no cover',
        'if __name__ == "__main__":',
]

[tool.pytest.ini_options]
addopts = """
-vv
--ignore=docs
--diff-type=split
--cov=scripts
--cov-report=term
--cov-report=xml
--typeguard-packages=scripts
"""

[tool.isort]
profile = "black"
skip_gitignore = true
float_to_top = false

[tool.flake8]
select = "ANN,B,B9,C,C4,D,DAR,F,S,SC"
ignore = "ANN101"
exclude = "docs/conf.py"
per-file-ignore = "tests/*:S101"
max-line-length = 88
max-complexity = 10
docstring-convention = "numpy"
docstring-style = "numpy"
strictness = "short"
dictionaries = "en_US,python,technical"
spellcheck-targets = "comments"
