[tool.coverage.run]
branch = true
source = ["scripts"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = """
-vv
--ignore=docs
--diff-type=split
--cov=scripts
--typeguard-packages=scripts
"""

[tool.isort]
profile = "black"
skip_gitignore = true
float_to_top = false

[tool.flake8]
select = "ANN,B,B9,C,C4,D,DAR,F,S,SC"
ignore = "ANN101"
exclude = "docs/conf.py"
per-file-ignore = "tests/*:S101"
max-line-length = 88
max-complexity = 10
docstring-convention = "numpy"
docstring-style = "numpy"
strictness = "short"
dictionaries = "en_US,python,technical"
spellcheck-targets = "comments"
